[package]
name = "wasm_local_fs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
wasm_vfs = { path = "../wasm_vfs" }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "junkyard-vfs:wasm-local-fs"

[package.metadata.component.dependencies]
