[package]
name = "wasm_local_fs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
vfs = { path = "../vfs" }
wasm_vfs = { path = "../wasm_vfs" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component]
package = "junkyard-vfs:wasm-local-fs"

[package.metadata.component.dependencies]
