[package]
name = "wasm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
vfs = { path = "../filesystem/vfs" }
wasm_vfs_api = { path = "../wasm_vfs_api" }
anyhow = "1.0.95"
wasmtime = { version = "29.0.1", default-features = false, features = ["runtime", "component-model", "cranelift"] }
wasmtime-wasi = "29.0.1"
sha256 = { version = "1.5.0", default-features = false }
